export const HIDE_NAVIGATOR = 'HIDE_NAVIGATOR';
export const NAVIGATE_TO = 'NAVIGATE_TO';
export const SHOW_NAVIGATOR = 'SHOW_NAVIGATOR';
export const UPDATE_CURRENT_PATHNAME = 'UPDATE_CURRENT_PATHNAME';
export const UPDATE_SCENE = 'UPDATE_SCENE';
