export const DISMISS_ERROR_MESSAGE = 'DISMISS_ERROR_MESSAGE';
export const DISMISS_SUCCESS_MESSAGE = 'DISMISS_SUCCESS_MESSAGE';
export const FLASH_ERROR_MESSAGE = 'FLASH_ERROR_MESSAGE';
export const FLASH_SUCCESS_MESSAGE = 'FLASH_SUCCESS_MESSAGE';
export const UPDATE_LOADING = 'UPDATE_LOADING';
